apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvs
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "__KUBELET_CLIENT_ID__"
    keyvaultName: "__KEY_VAULT_NAME__"
    objects: |
      array:
        - |
          objectName: pg-admin-password
          objectType: secret
        - |
          objectName: pg-admin-login
          objectType: secret
        - |
          objectName: pg-host
          objectType: secret
    tenantId: "__TENANT_ID__"
  secretObjects:
    - secretName: pg-secrets
      type: Opaque
      data:
        - objectName: pg-admin-password
          key: PG_PASSWORD
        - objectName: pg-admin-login
          key: PG_USERNAME
        - objectName: pg-host
          key: PG_HOST
